/*
 * Performance Monitoring Unit Events
 *
 * Copyright (c) Universita' di Modena e Reggio Emilia, 2020
 * Copyright (C) 2012 ARM Ltd.
 *
 * Authors:
 *  Luca Miccio <lucmiccio@gmail.com>
 *
 * PMU defines copied from
 * arch/arm64/include/asm/perf_event.h in Linux
 *
 * This work is licensed under the terms of the GNU GPL, version 2.  See
 * the COPYING file in the top-level directory.
 */
#ifndef _PMU_EVENTS_H
#define _PMU_EVENTS_H

#define	PMU_MAX_COUNTERS	32
#define	PMU_COUNTER_MASK	(PMU_MAX_COUNTERS - 1)

/*
 * Common architectural and microarchitectural event numbers.
 */
#define PMUV3_PERFCTR_SW_INCR				0x00
#define PMUV3_PERFCTR_L1I_CACHE_REFILL			0x01
#define PMUV3_PERFCTR_L1I_TLB_REFILL			0x02
#define PMUV3_PERFCTR_L1D_CACHE_REFILL			0x03
#define PMUV3_PERFCTR_L1D_CACHE				0x04
#define PMUV3_PERFCTR_L1D_TLB_REFILL			0x05
#define PMUV3_PERFCTR_LD_RETIRED			0x06
#define PMUV3_PERFCTR_ST_RETIRED			0x07
#define PMUV3_PERFCTR_INST_RETIRED			0x08
#define PMUV3_PERFCTR_EXC_TAKEN				0x09
#define PMUV3_PERFCTR_EXC_RETURN			0x0A
#define PMUV3_PERFCTR_CID_WRITE_RETIRED			0x0B
#define PMUV3_PERFCTR_PC_WRITE_RETIRED			0x0C
#define PMUV3_PERFCTR_BR_IMMED_RETIRED			0x0D
#define PMUV3_PERFCTR_BR_RETURN_RETIRED			0x0E
#define PMUV3_PERFCTR_UNALIGNED_LDST_RETIRED		0x0F
#define PMUV3_PERFCTR_BR_MIS_PRED			0x10
#define PMUV3_PERFCTR_CPU_CYCLES			0x11
#define PMUV3_PERFCTR_BR_PRED				0x12
#define PMUV3_PERFCTR_MEM_ACCESS			0x13
#define PMUV3_PERFCTR_L1I_CACHE				0x14
#define PMUV3_PERFCTR_L1D_CACHE_WB			0x15
#define PMUV3_PERFCTR_L2D_CACHE				0x16
#define PMUV3_PERFCTR_L2D_CACHE_REFILL			0x17
#define PMUV3_PERFCTR_L2D_CACHE_WB			0x18
#define PMUV3_PERFCTR_BUS_ACCESS			0x19
#define PMUV3_PERFCTR_MEMORY_ERROR			0x1A
#define PMUV3_PERFCTR_INST_SPEC				0x1B
#define PMUV3_PERFCTR_TTBR_WRITE_RETIRED		0x1C
#define PMUV3_PERFCTR_BUS_CYCLES			0x1D
#define PMUV3_PERFCTR_CHAIN				0x1E
#define PMUV3_PERFCTR_L1D_CACHE_ALLOCATE		0x1F
#define PMUV3_PERFCTR_L2D_CACHE_ALLOCATE		0x20
#define PMUV3_PERFCTR_BR_RETIRED			0x21
#define PMUV3_PERFCTR_BR_MIS_PRED_RETIRED		0x22
#define PMUV3_PERFCTR_STALL_FRONTEND			0x23
#define PMUV3_PERFCTR_STALL_BACKEND			0x24
#define PMUV3_PERFCTR_L1D_TLB				0x25
#define PMUV3_PERFCTR_L1I_TLB				0x26
#define PMUV3_PERFCTR_L2I_CACHE				0x27
#define PMUV3_PERFCTR_L2I_CACHE_REFILL			0x28
#define PMUV3_PERFCTR_L3D_CACHE_ALLOCATE		0x29
#define PMUV3_PERFCTR_L3D_CACHE_REFILL			0x2A
#define PMUV3_PERFCTR_L3D_CACHE				0x2B
#define PMUV3_PERFCTR_L3D_CACHE_WB			0x2C
#define PMUV3_PERFCTR_L2D_TLB_REFILL			0x2D
#define PMUV3_PERFCTR_L2I_TLB_REFILL			0x2E
#define PMUV3_PERFCTR_L2D_TLB				0x2F
#define PMUV3_PERFCTR_L2I_TLB				0x30
#define PMUV3_PERFCTR_REMOTE_ACCESS			0x31
#define PMUV3_PERFCTR_LL_CACHE				0x32
#define PMUV3_PERFCTR_LL_CACHE_MISS			0x33
#define PMUV3_PERFCTR_DTLB_WALK				0x34
#define PMUV3_PERFCTR_ITLB_WALK				0x35
#define PMUV3_PERFCTR_LL_CACHE_RD			0x36
#define PMUV3_PERFCTR_LL_CACHE_MISS_RD			0x37
#define PMUV3_PERFCTR_REMOTE_ACCESS_RD			0x38

/* Statistical profiling extension microarchitectural events */
#define	SPE_PERFCTR_SAMPLE_POP				0x4000
#define	SPE_PERFCTR_SAMPLE_FEED				0x4001
#define	SPE_PERFCTR_SAMPLE_FILTRATE			0x4002
#define	SPE_PERFCTR_SAMPLE_COLLISION			0x4003

/* ARMv8 recommended implementation defined event types */
#define IMPDEF_PERFCTR_L1D_CACHE_RD			0x40
#define IMPDEF_PERFCTR_L1D_CACHE_WR			0x41
#define IMPDEF_PERFCTR_L1D_CACHE_REFILL_RD		0x42
#define IMPDEF_PERFCTR_L1D_CACHE_REFILL_WR		0x43
#define IMPDEF_PERFCTR_L1D_CACHE_REFILL_INNER		0x44
#define IMPDEF_PERFCTR_L1D_CACHE_REFILL_OUTER		0x45
#define IMPDEF_PERFCTR_L1D_CACHE_WB_VICTIM		0x46
#define IMPDEF_PERFCTR_L1D_CACHE_WB_CLEAN		0x47
#define IMPDEF_PERFCTR_L1D_CACHE_INVAL			0x48

#define IMPDEF_PERFCTR_L1D_TLB_REFILL_RD		0x4C
#define IMPDEF_PERFCTR_L1D_TLB_REFILL_WR		0x4D
#define IMPDEF_PERFCTR_L1D_TLB_RD			0x4E
#define IMPDEF_PERFCTR_L1D_TLB_WR			0x4F
#define IMPDEF_PERFCTR_L2D_CACHE_RD			0x50
#define IMPDEF_PERFCTR_L2D_CACHE_WR			0x51
#define IMPDEF_PERFCTR_L2D_CACHE_REFILL_RD		0x52
#define IMPDEF_PERFCTR_L2D_CACHE_REFILL_WR		0x53

#define IMPDEF_PERFCTR_L2D_CACHE_WB_VICTIM		0x56
#define IMPDEF_PERFCTR_L2D_CACHE_WB_CLEAN		0x57
#define IMPDEF_PERFCTR_L2D_CACHE_INVAL			0x58

#define IMPDEF_PERFCTR_L2D_TLB_REFILL_RD		0x5C
#define IMPDEF_PERFCTR_L2D_TLB_REFILL_WR		0x5D
#define IMPDEF_PERFCTR_L2D_TLB_RD			0x5E
#define IMPDEF_PERFCTR_L2D_TLB_WR			0x5F
#define IMPDEF_PERFCTR_BUS_ACCESS_RD			0x60
#define IMPDEF_PERFCTR_BUS_ACCESS_WR			0x61
#define IMPDEF_PERFCTR_BUS_ACCESS_SHARED		0x62
#define IMPDEF_PERFCTR_BUS_ACCESS_NOT_SHARED		0x63
#define IMPDEF_PERFCTR_BUS_ACCESS_NORMAL		0x64
#define IMPDEF_PERFCTR_BUS_ACCESS_PERIPH		0x65
#define IMPDEF_PERFCTR_MEM_ACCESS_RD			0x66
#define IMPDEF_PERFCTR_MEM_ACCESS_WR			0x67
#define IMPDEF_PERFCTR_UNALIGNED_LD_SPEC		0x68
#define IMPDEF_PERFCTR_UNALIGNED_ST_SPEC		0x69
#define IMPDEF_PERFCTR_UNALIGNED_LDST_SPEC		0x6A

#define IMPDEF_PERFCTR_LDREX_SPEC			0x6C
#define IMPDEF_PERFCTR_STREX_PASS_SPEC			0x6D
#define IMPDEF_PERFCTR_STREX_FAIL_SPEC			0x6E
#define IMPDEF_PERFCTR_STREX_SPEC			0x6F
#define IMPDEF_PERFCTR_LD_SPEC				0x70
#define IMPDEF_PERFCTR_ST_SPEC				0x71
#define IMPDEF_PERFCTR_LDST_SPEC			0x72
#define IMPDEF_PERFCTR_DP_SPEC				0x73
#define IMPDEF_PERFCTR_ASE_SPEC				0x74
#define IMPDEF_PERFCTR_VFP_SPEC				0x75
#define IMPDEF_PERFCTR_PC_WRITE_SPEC			0x76
#define IMPDEF_PERFCTR_CRYPTO_SPEC			0x77
#define IMPDEF_PERFCTR_BR_IMMED_SPEC			0x78
#define IMPDEF_PERFCTR_BR_RETURN_SPEC			0x79
#define IMPDEF_PERFCTR_BR_INDIRECT_SPEC			0x7A

#define IMPDEF_PERFCTR_ISB_SPEC				0x7C
#define IMPDEF_PERFCTR_DSB_SPEC				0x7D
#define IMPDEF_PERFCTR_DMB_SPEC				0x7E

#define IMPDEF_PERFCTR_EXC_UNDEF			0x81
#define IMPDEF_PERFCTR_EXC_SVC				0x82
#define IMPDEF_PERFCTR_EXC_PABORT			0x83
#define IMPDEF_PERFCTR_EXC_DABORT			0x84

#define IMPDEF_PERFCTR_EXC_IRQ				0x86
#define IMPDEF_PERFCTR_EXC_FIQ				0x87
#define IMPDEF_PERFCTR_EXC_SMC				0x88

#define IMPDEF_PERFCTR_EXC_HVC				0x8A
#define IMPDEF_PERFCTR_EXC_TRAP_PABORT			0x8B
#define IMPDEF_PERFCTR_EXC_TRAP_DABORT			0x8C
#define IMPDEF_PERFCTR_EXC_TRAP_OTHER			0x8D
#define IMPDEF_PERFCTR_EXC_TRAP_IRQ			0x8E
#define IMPDEF_PERFCTR_EXC_TRAP_FIQ			0x8F
#define IMPDEF_PERFCTR_RC_LD_SPEC			0x90
#define IMPDEF_PERFCTR_RC_ST_SPEC			0x91

#define IMPDEF_PERFCTR_L3D_CACHE_RD			0xA0
#define IMPDEF_PERFCTR_L3D_CACHE_WR			0xA1
#define IMPDEF_PERFCTR_L3D_CACHE_REFILL_RD		0xA2
#define IMPDEF_PERFCTR_L3D_CACHE_REFILL_WR		0xA3

#define IMPDEF_PERFCTR_L3D_CACHE_WB_VICTIM		0xA6
#define IMPDEF_PERFCTR_L3D_CACHE_WB_CLEAN		0xA7
#define IMPDEF_PERFCTR_L3D_CACHE_INVAL			0xA8

#endif
